name: Test Typst Install Script

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitattributes
      - .gitignore
      - .github/**
      - "!.github/workflows/ci.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitattributes
      - .gitignore
      - .github/**
      - "!.github/workflows/ci.yml"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck scripts/install.sh
  install-sh:
    needs: shellcheck
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/install.sh
      - run: echo "$HOME/.typst/bin" >> "$GITHUB_PATH"
      - run: typst --version
      - run: typst compile scripts/test/test.typ
  install-ps1:
    needs: shellcheck
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwsh scripts/install.ps1
          echo "$HOME\.typst\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: typst --version
      - run: typst compile scripts/test/test.typ
