name: Test Typst Install Script

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck scripts/install.sh

  POSIX:
    needs: shellcheck
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install Typst via script
        run: curl -fsSL https://jassielof.github.io/typst-install/install.sh | bash
      - run: echo "$HOME/.typst/bin" >> "$GITHUB_PATH"
      - run: typst --version
      - run: typst compile scripts/test/test.typ

  Windows-pwsh7:
    name: "Windows (pwsh 7)"
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst via script (pwsh 7)
        run: irm https://jassielof.github.io/typst-install/install.ps1 | iex
      - name: Check typst version
        run: typst --version

      - name: Compile test.typ
        run: typst compile scripts/test/test.typ

  Windows-PowerShell5:
    name: "Windows (PowerShell 5.1)"
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst via script (PowerShell 5.1)
        run: irm https://jassielof.github.io/typst-install/install.ps1 | iex
        
      - name: Check typst version
        run: typst --version

      - name: Compile test.typ
        run: typst compile scripts/test/test.typ
