name: Test Typst Install Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck scripts/install.sh

  POSIX:
    # No changes needed here, but keeping it for context
    needs: shellcheck
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install Typst via script
        # This can be changed to use the local script too for consistency!
        run: |
          cat ./scripts/install.sh | bash
      - run: echo "$HOME/.typst/bin" >> "$GITHUB_PATH"
      - run: typst --version
      - run: typst compile scripts/test/test.typ

  Windows-pwsh7: # Renamed for clarity
    name: "Windows (pwsh 7)"
    needs: shellcheck
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh # Use modern PowerShell
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst via script (pwsh 7)
        run: |
          Get-Content ./scripts/install.ps1 -Raw | Invoke-Expression
          # No need to add to GITHUB_PATH here, the script already does it.

      - name: Check typst version
        run: typst --version

      - name: Compile test.typ
        run: typst compile scripts/test/test.typ

  Windows-PowerShell5:
    name: "Windows (PowerShell 5.1)"
    needs: shellcheck
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell # Use Windows PowerShell 5.1
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst via script (PowerShell 5.1)
        run: |
          Get-Content ./scripts/install.ps1 -Raw | Invoke-Expression
          # No need to add to GITHUB_PATH here, the script already does it.

      - name: Check typst version
        run: typst --version

      - name: Compile test.typ
        run: typst compile scripts/test/test.typ
