name: Test Typst Install Script

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck scripts/install.sh

  POSIX:
    needs: shellcheck
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install Typst via script
        run: |
          curl -fsSL https://jassielof.github.io/typst-install/install.sh | bash
      - run: echo "$HOME/.typst/bin" >> "$GITHUB_PATH"
      - run: typst --version
      - run: typst compile scripts/test/test.typ

  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Typst via script
        run: |
          irm https://jassielof.github.io/typst-install/install.ps1 | iex
          echo "$HOME\.typst\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: typst --version
      - run: typst compile scripts/test/test.typ

  Windows-PowerShell5:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Typst via script (PowerShell 5.1)
        shell: powershell
        run: |
          irm https://jassielof.github.io/typst-install/install.ps1 | iex
          "$HOME\.typst\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: Check typst version
        shell: powershell
        run: typst --version
      - name: Compile test.typ
        shell: powershell
        run: typst compile scripts/test/test.typ
