name: Test
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/install_test.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/install_test.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck install.sh
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: cat install.sh | sh
      - shell: bash
        run: echo "$HOME/.typst/bin" >> "$GITHUB_PATH"
      - run: typst --version
      - run: typst compile test.typ
  install-ps1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: type install.ps1 | iex
      - run: typst --version
      - run: typst compile test.typ
